Name: Webserver Service
Description: A webserver service
Author: jan gehring <jan.gehring@gmail.com>
License: Apache 2.0
Require:
  Apache:
    git: https://github.com/RexOps/rex-apache.git
    branch: master
